### ISSUE TITLE
issue with adding tears in retistruct

### ISSUE THREAD

**Issue by sagewiltse** [davidcsterratt/retistruct#11]
After some issues with downloading the retistruct package onto my Mac, we were able to go through until it came to opening the outline.roi in retistruct. I was able to open the outline, but it wouldn't let me add a tear or indicate nasal. I am working with Brian Cohn and he said to come here. Let me know and any help is appreciated. 
<img width="880" alt="screen shot 2017-06-16 at 11 50 48 am" src="https://user-images.githubusercontent.com/29490961/27240657-8461c872-528a-11e7-9ee4-bd9bfa1d0232.png">
<img width="1234" alt="screen shot 2017-06-16 at 11 54 18 am" src="https://user-images.githubusercontent.com/29490961/27240675-9135cd6e-528a-11e7-8730-e2f594583687.png">

**Comment by briancohn** [comment]
@sagewiltse please upload your outline.roi as well

**Comment by davidcsterratt** [comment]
Hmm.... That's interesting. The outline.roi file would be useful. Also, after you get the error, could you type "traceback()" in the R console, and send me the output please?

**Comment by sagewiltse** [comment]
Here is what I got when I typed in "traceback()" and the outline.roi file.
Let me know your thoughts, and I appriciate the help.

-Sage Wiltse

On Mon, Jun 19, 2017 at 10:01 AM, David C Sterratt <notifications@github.com

**Comment by davidcsterratt** [comment]
I can't see the output on the github website - please could you try posting it again.

**Comment by davidcsterratt** [comment]
I think this might be fixed in the next version of Retistruct, 0.5.11, which I am working on now.

**Comment by sagewiltse** [comment]
Here is the output. Thank you for your help!
<img width="648" alt="screen shot 2017-06-19 at 10 07 48 am" src="https://user-images.githubusercontent.com/29490961/27352586-13fa7e1a-55b6-11e7-9db8-5ff2ad0ff69b.png">

**Comment by briancohn** [comment]
@davidcsterratt what do you think? which functions/libraries are most likely responsible for this issue?

**Comment by briancohn** [comment]
@davidcsterratt Many of our retina package users are getting blocked in trying to use retistruct in our package. Could you please publish a version of retistruct that does not include the graphic user interface, and with no dependencies to gWidgets, RGTK2, etc?

Brian

**Comment by davidcsterratt** [comment]
Hello Brian, sorry for the delay getting the latest version of Retistruct onto CRAN. I have been having problems because of getting the RTriangle package to compile on Windows x86 (#14). Are you sure it's RGTk that is blocking users or RTriangle?

In any case the current stable version (0.5.10) doesn't actually depend on RGK2, gWidgets &c; these are "Suggests", so users should still be able to install Retistruct without installing the other packages. They are only installed when the GUI is started using retistruct(). If you can mark up a retina without using the interface, then retisturct.reconstruct(`directory_name`) can be called to reconstruct the retina from the files in `directory_name`.

The current development version is available to download from GitHub on the master branch, and this should fix the problem here. It should work now that #13 has been fixed by a change to gWidgets2. 

Apologies again - there is a bit of dependency hell at the moment!

**Comment by davidcsterratt** [comment]
I've managed to get Retistruct on CRAN, so you should be able to install it using:
```install.packages("retistruct")```
You may also need
```install.packages("gWidgets2RGtk2")```
Also, you may need to wait a day or two for this to work for Windows, as it takes a while for CRAN to build the packages and for them to reach mirrors.
